// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

import { Observer } from "rxjs";
import { ChatItem } from "./renderer/models/ChatItem";
import { Server } from "./renderer/models/Server";
import { Session } from "./renderer/models/Session";
import OpenAI from "openai";

// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

declare const SETTING_WINDOW_VITE_DEV_SERVER_URL: string;
declare const SETTING_WINDOW_VITE_NAME: string;

declare global {
  interface Window {
    settingsIpc: {
      onTabChange: (onChange: (tab: string) => void) => void;
      showWindow: (tab: string) => void;
      themeChange: (theme: string) => void;
      onThemeChange: (callback: (theme: string) => void) => void;
      alert: (type: string, title: string, message: string) => void;
    };
    mainIpc: {
      selectImages: () => void;
      onSelectImages: (
        callback: (imgs: { url: string; content: string }[]) => void,
      ) => void;
      minimize: () => void;
      maximize: () => void;
      unmaximize: () => void;
      close: () => void;
      showAbout: () => void;
      onCreateChat: (callback: () => void) => void;
      export: (name: string, chats: string[]) => void;
    };
    env: {
      getPlatform: () => string;
    };
  }
}
